# To run steps listed in the readme

#To create the simulated datasets from the real datasets used in the paper, first run the code in [simFunction.R](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/simFunction.R). Then, run the `.R` files in the folders in `sims/figures`. Finally, run [figuresPaper.Rmd](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/figuresPaper.Rmd).

Rscript sims/figures/simFunction.R
Rscript sims/figures/fig6e-g/lunSim.R
Rscript sims/figures/fig6e-g/fitZinbLun.R
Rscript sims/figures/fig5-S10-S11-S15-S9/timeZinb.R
Rscript sims/figures/fig5-S10-S11-S15-S9/fitZinb_bias_mse_ncells.R
Rscript sims/figures/fig5-S10-S11-S15-S9/fitZinb_bias_mse_allParam.R
Rscript sims/figures/fig6ad-S13-S14/fitZifa_allen_10000.R
Rscript sims/figures/fig6ad-S13-S14/fitZifa_zeisel_10000.R
Rscript sims/figures/fig6ad-S13-S14/fitZifa.R
Rscript sims/figures/fig6ad-S13-S14/fitZinb_corSilh.R
Rscript sims/figures/fig6ad-S13-S14/fitZinb10000.R

#To simulate the datasets from the Lun & Marioni model, run [lunSim.R](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/fig6e-g/lunSim.R). It uses file [function.rds](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/fig6e-g/function.rds) generated by the steps described in the Methods section of the paper. Then, run [fitZinbLun.R](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/fig6e-g/fitZinbLun.R).

#To fit the simulated datasets with n=10,000 cells, we used a [Makefile](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/fig6ad-S13-S14/Makefile) to launch jobs on a server. Alternatively, you can just call [fitZinb10000.R](https://github.com/drisso/zinb_analysis/blob/master/sims/figures/fig6ad-S13-S14/fitZinb10000.R) from your terminal with the arguments you want.
